services:
  berengario-www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: berengario-www
    restart: unless-stopped

    expose:
      - "80"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - intranet

networks:
  intranet:
    external: true
