"""
Email sender module for sending automated replies via SMTP.

Handles SMTP connection, email composition, and sending with proper error handling.
"""

import logging
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Dict, List, Optional

import markdown

from src.config import settings

logger = logging.getLogger(__name__)


def load_custom_footer(instance_name: str) -> tuple[str, str]:
    """
    Load custom footer or use default.

    Args:
        instance_name: Name of the instance for default footer

    Returns:
        Tuple of (plain_text_footer, html_footer)
    """
    if settings.email_custom_footer_file and settings.email_custom_footer_file.exists():
        try:
            with open(settings.email_custom_footer_file, "r", encoding="utf-8") as f:
                footer_text = f.read().strip()

            if footer_text:
                # Plain text version
                plain_footer = f"\n\n---\n{footer_text}"

                # HTML version (convert newlines to <br>)
                html_footer = (
                    f'<div class="footer">{footer_text.replace(chr(10), "<br>")}</div>'
                )

                logger.info(
                    f"Loaded custom footer from {settings.email_custom_footer_file}"
                )
                return plain_footer, html_footer
        except Exception as e:
            logger.warning(f"Failed to load custom footer file: {e}")

    # Default footer
    plain_footer = f"\n\n---\nThis response was generated by {instance_name}.\nIf you have follow-up questions, simply reply to this email."
    html_footer = f"""<div class="footer">
        <p>This response was generated by <strong>{instance_name}</strong>.</p>
        <p>If you have follow-up questions, simply reply to this email.</p>
    </div>"""

    return plain_footer, html_footer


class EmailSender:
    """
    Handles sending email responses via SMTP.

    Supports TLS/SSL connections and HTML/plain text email composition.

    Attributes:
        smtp_server: SMTP server address
        smtp_port: SMTP server port
        smtp_user: SMTP username
        smtp_password: SMTP password
        use_tls: Whether to use TLS encryption
        from_address: Sender email address
        from_name: Sender display name
    """

    def __init__(
        self,
        smtp_server: Optional[str] = None,
        smtp_port: Optional[int] = None,
        smtp_user: Optional[str] = None,
        smtp_password: Optional[str] = None,
        use_tls: Optional[bool] = None,
        from_address: Optional[str] = None,
        from_name: Optional[str] = None,
    ):
        """
        Initialize email sender.

        Args:
            smtp_server: SMTP server address (defaults to settings)
            smtp_port: SMTP port (defaults to settings)
            smtp_user: SMTP username (defaults to settings)
            smtp_password: SMTP password (defaults to settings)
            use_tls: Use TLS encryption (defaults to settings)
            from_address: Sender email address (defaults to settings)
            from_name: Sender display name (defaults to settings)
        """
        self.smtp_server = smtp_server or settings.smtp_server
        self.smtp_port = smtp_port or settings.smtp_port
        self.smtp_user = smtp_user or settings.smtp_user
        self.smtp_password = smtp_password or settings.smtp_password
        self.use_tls = use_tls if use_tls is not None else settings.smtp_use_tls
        self.from_address = from_address or settings.email_target_address
        self.from_name = from_name or settings.email_display_name

        logger.info(
            f"EmailSender initialized: {self.smtp_server}:{self.smtp_port} "
            f"(TLS: {self.use_tls})"
        )

    @staticmethod
    def _format_message_id(msg_id: str) -> str:
        """
        Ensure Message-ID is properly formatted with angle brackets.

        Args:
            msg_id: Message ID string

        Returns:
            Message ID enclosed in angle brackets if not already.
        """
        if not msg_id:
            return msg_id
        msg_id = msg_id.strip()
        # Add angle brackets if not present
        if not msg_id.startswith("<"):
            msg_id = "<" + msg_id
        if not msg_id.endswith(">"):
            msg_id = msg_id + ">"
        return msg_id

    def send_reply(
        self,
        to_address: str,
        subject: str,
        body_text: str,
        body_html: Optional[str] = None,
        in_reply_to: Optional[str] = None,
        references: Optional[List[str]] = None,
        attachments: Optional[List[Dict[str, any]]] = None,
    ) -> bool:
        """
        Send an email reply.

        Args:
            to_address: Recipient email address
            subject: Email subject line
            body_text: Plain text email body
            body_html: HTML email body (optional)
            in_reply_to: Message-ID of email being replied to
            references: List of message IDs in conversation thread
            attachments: List of attachments, each dict with 'content' (bytes or str),
                        'filename' (str), and optional 'content_type' (str)

        Returns:
            True if email sent successfully, False otherwise.
        """
        try:
            # Create message - use "mixed" if attachments, otherwise "alternative"
            if attachments:
                msg = MIMEMultipart("mixed")
            else:
                msg = MIMEMultipart("alternative")

            msg["From"] = f"{self.from_name} <{self.from_address}>"
            msg["To"] = to_address
            msg["Subject"] = subject

            # Add threading headers for proper conversation grouping
            # Ensure Message-IDs are properly formatted with angle brackets (RFC 5322)
            if in_reply_to:
                formatted_in_reply_to = self._format_message_id(in_reply_to)
                msg["In-Reply-To"] = formatted_in_reply_to
                logger.info(f"Setting In-Reply-To header: {formatted_in_reply_to}")
            if references:
                # Format each reference and join with space
                formatted_refs = [self._format_message_id(ref) for ref in references]
                msg["References"] = " ".join(formatted_refs)
                logger.info(f"Setting References header: {' '.join(formatted_refs)}")

            logger.info(f"Sending email with Subject: {subject}")

            # Create body container (for text alternatives)
            if attachments:
                body_container = MIMEMultipart("alternative")
            else:
                body_container = msg

            # Attach plain text version
            text_part = MIMEText(body_text, "plain", "utf-8")
            body_container.attach(text_part)

            # Attach HTML version if provided
            if body_html:
                html_part = MIMEText(body_html, "html", "utf-8")
                body_container.attach(html_part)

            # Attach body container if we have attachments
            if attachments:
                msg.attach(body_container)

            # Attach files
            if attachments:
                for attachment in attachments:
                    content = attachment.get("content")
                    filename = attachment.get("filename", "attachment")
                    content_type = attachment.get(
                        "content_type", "application/octet-stream"
                    )

                    # Convert string content to bytes if needed
                    if isinstance(content, str):
                        content = content.encode("utf-8")

                    part = MIMEBase(*content_type.split("/", 1))
                    part.set_payload(content)
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition", f'attachment; filename="{filename}"'
                    )
                    msg.attach(part)

                    logger.debug(f"Attached file: {filename} ({content_type})")

            # Connect to SMTP server
            logger.info(
                f"Connecting to SMTP server: {self.smtp_server}:{self.smtp_port}"
            )

            if self.use_tls:
                # Use STARTTLS (port 587)
                smtp = smtplib.SMTP(self.smtp_server, self.smtp_port, timeout=30)
                smtp.ehlo()
                smtp.starttls()
                smtp.ehlo()
            else:
                # Direct connection (port 25 or 465 for SSL)
                smtp = smtplib.SMTP(self.smtp_server, self.smtp_port, timeout=30)

            # Authenticate
            logger.debug(f"Authenticating as {self.smtp_user}")
            smtp.login(self.smtp_user, self.smtp_password)

            # Send email
            smtp.send_message(msg)
            smtp.quit()

            logger.info(f"Successfully sent email to {to_address}: {subject}")
            return True

        except smtplib.SMTPAuthenticationError as e:
            logger.error(f"SMTP authentication failed: {e}")
            return False
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error sending email: {e}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error sending email: {e}", exc_info=True)
            return False

    def test_connection(self) -> bool:
        """
        Test SMTP connection and authentication.

        Returns:
            True if connection successful, False otherwise.
        """
        try:
            logger.info(
                f"Testing SMTP connection to {self.smtp_server}:{self.smtp_port}"
            )

            if self.use_tls:
                smtp = smtplib.SMTP(self.smtp_server, self.smtp_port, timeout=30)
                smtp.ehlo()
                smtp.starttls()
                smtp.ehlo()
            else:
                smtp = smtplib.SMTP(self.smtp_server, self.smtp_port, timeout=30)

            smtp.login(self.smtp_user, self.smtp_password)
            smtp.quit()

            logger.info("SMTP connection test successful")
            return True

        except Exception as e:
            logger.error(f"SMTP connection test failed: {e}")
            return False


def format_response_email(
    response_text: str,
    sources: List[dict],
    instance_name: str,
    original_subject: str,
) -> tuple[str, str, str]:
    """
    Format RAG response into email-friendly text and HTML.

    Supports three formats based on EMAIL_RESPONSE_FORMAT setting:
    - 'text': Plain text only
    - 'markdown': Markdown syntax in plain text
    - 'html': Styled HTML (default)

    Args:
        response_text: RAG-generated response text
        sources: List of source documents with metadata
        instance_name: Name of the RAG instance
        original_subject: Original email subject

    Returns:
        Tuple of (subject, plain_text_body, html_body).
    """
    # Prepare subject line
    if not original_subject.lower().startswith("re:"):
        subject = f"Re: {original_subject}"
    else:
        subject = original_subject

    # Load custom footer
    plain_footer, html_footer = load_custom_footer(instance_name)

    # Get email format from settings
    email_format = settings.email_response_format.lower()

    # Format based on selected format
    if email_format == "text":
        # Plain text only format
        plain_text, html_body = _format_text_email(response_text, sources, plain_footer)
    elif email_format == "markdown":
        # Markdown format
        plain_text, html_body = _format_markdown_email(
            response_text, sources, plain_footer
        )
    else:  # html (default)
        # HTML format with styling
        plain_text, html_body = _format_html_email(
            response_text, sources, plain_footer, html_footer
        )

    return subject, plain_text, html_body


def _format_text_email(
    response_text: str, sources: List[dict], plain_footer: str
) -> tuple[str, str]:
    """Format email as plain text."""
    # Format sources
    sources_text = ""
    if sources:
        sources_text = "\n\nSources:\n"
        for idx, source in enumerate(sources, 1):
            filename = source.get("filename", "Unknown document")
            score = source.get("score", 0)
            sources_text += f"{idx}. {filename} (relevance: {score:.2f})\n"

    # Plain text body
    plain_text = f"{response_text}{sources_text}{plain_footer}"

    # Minimal HTML fallback for compatibility
    html_body = f"<html><body><pre>{plain_text}</pre></body></html>"

    return plain_text, html_body


def _format_markdown_email(
    response_text: str, sources: List[dict], plain_footer: str
) -> tuple[str, str]:
    """Format email with markdown syntax."""
    # Format sources in markdown
    sources_text = ""
    if sources:
        sources_text = "\n\n## Sources\n\n"
        for idx, source in enumerate(sources, 1):
            filename = source.get("filename", "Unknown document")
            score = source.get("score", 0)
            sources_text += f"{idx}. **{filename}** (relevance: {score:.2f})\n"

    # Plain text body with markdown
    plain_text = f"{response_text}{sources_text}{plain_footer}"

    # Minimal HTML fallback
    html_body = f"<html><body><pre>{plain_text}</pre></body></html>"

    return plain_text, html_body


def _format_html_email(
    response_text: str,
    sources: List[dict],
    plain_footer: str,
    html_footer: str,
) -> tuple[str, str]:
    """Format email with styled HTML."""

    def format_source_display(source: dict) -> tuple[str, str]:
        """
        Format source information for display.

        Returns:
            Tuple of (plain_text_line, html_line)
        """
        # Check if this is an email source with metadata
        sender = source.get("sender")
        subject = source.get("subject")
        score = source.get("score", 0)

        if sender and subject:
            # Email source - show sender and subject
            plain = f'Email from {sender}: "{subject}" (relevance: {score:.2f})'
            html = f'<strong>Email from {sender}:</strong> "{subject}" <span style="color: #666;">(relevance: {score:.2f})</span>'
        elif subject:
            # Has subject but no sender
            plain = f'Email: "{subject}" (relevance: {score:.2f})'
            html = f'<strong>Email:</strong> "{subject}" <span style="color: #666;">(relevance: {score:.2f})</span>'
        else:
            # File source - show filename
            filename = source.get("filename", "Unknown document")
            plain = f"{filename} (relevance: {score:.2f})"
            html = f'<strong>{filename}</strong> <span style="color: #666;">(relevance: {score:.2f})</span>'

        return plain, html

    # Format sources for plain text
    sources_text = ""
    if sources:
        sources_text = "\n\nSources:\n"
        for idx, source in enumerate(sources, 1):
            plain, _ = format_source_display(source)
            sources_text += f"{idx}. {plain}\n"

    # Plain text version
    plain_text = f"{response_text}{sources_text}{plain_footer}"

    # Format sources for HTML
    sources_html = ""
    if sources:
        sources_html = "<h3>Sources:</h3><ul>"
        for source in sources:
            _, html = format_source_display(source)
            sources_html += f"<li>{html}</li>"
        sources_html += "</ul>"

    # Convert markdown response to HTML
    response_html = markdown.markdown(
        response_text, extensions=["extra", "nl2br", "sane_lists"]
    )

    # Build HTML version with styling
    html_body = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        .response {{
            margin-bottom: 20px;
        }}
        .response h3 {{
            margin-top: 0;
            color: #333;
        }}
        .response strong {{
            color: #2c3e50;
        }}
        .sources {{
            margin-bottom: 20px;
        }}
        .sources h3 {{
            margin-top: 0;
            color: #333;
        }}
        .sources ul {{
            margin: 10px 0;
            padding-left: 20px;
        }}
        .footer {{
            border-top: 1px solid #ddd;
            padding-top: 15px;
            margin-top: 20px;
            font-size: 0.9em;
            color: #666;
        }}
    </style>
</head>
<body>
    <div class="response">
        {response_html}
    </div>

    {f'<div class="sources">{sources_html}</div>' if sources else ''}

    {html_footer}
</body>
</html>
"""

    return plain_text, html_body


# Global email sender instance
email_sender = EmailSender()
